# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: prettier
        name: prettier (system)
        entry: prettier --write --ignore-unknown
        language: node
  - repo: local
    hooks:
      - id: eslint
        name: eslint (system)
        entry: npx eslint
        language: system
        types: [file]
        files: \.[jt]sx?$
